from django.urls import include, path
from rest_framework.routers import DefaultRouter
from .views import AssetViewSet, ProjectViewSet

# DRF (Django REST Framework)

# Initialize the DRF DefaultRouter
router = DefaultRouter()
router.register(r'projects', ProjectViewSet, basename='project')
router.register(r'assets', AssetViewSet, basename='asset')

urlpatterns = [
    # Include all routes generated by the router automatically
    path('', include(router.urls)),
]